### ISSUE TITLE
Follow up on slow OSX paint performance

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej#127]
http://imagej.sourceforge.net/docs/install/osx.html refers to bug #2720543 file with Apple regarding ImageJ's slow paint performance on OSX. Supposedly this is fixed but I wasn't able to find a public reference to this bug - so we should make sure it truly is fixed in newer Apple Javas.

**Comment by ctrueden** [comment]
Whoa, hold on. That document looks super old. It is talking about performance of OS X when it _first came out_, as compared to _OS 9_.

There is a different painting bug, which manifests with Oracle Java 8 (and I think Java 7 too?). As of `1.8.0_45` the problem seems to be fixed. (`1.8.0_11` still had the issue—not sure exactly which version fixed it.)

See also [Fiji bug #965](http://fiji.sc/bugzilla/show_bug.cgi?id=965).

**Comment by ctrueden** [comment]
So anyway: paint performance fixed! Thank you Oracle! :grin:
