### ISSUE TITLE
"result" window opening after executing macro

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej#148]
Hey guys,

since the last update, I have the issue that a "results" window opens whenever I run a macro. The macro can be as simple as "i = 5;". When I run it, a window opens which has "result" as title and -17974594 as content. If I execute the macro "result = 5;" then a window opens with 5 as content.

If I run a Jython script "result = 5", I get the error message "[WARNING] Ignoring unsupported output: result [org.python.core.PyInteger]" on the console.

Could this be turned off somehow?

I'm using (FIJI Is Just) ImageJ 2.0.0-rc-52/1.51f; Java 1.8.0_66 [64-bit] on MacOS 10.10.5

Thanks!
Robert

**Comment by ctrueden** [comment]
Thanks for the report, @haesleinhuepf. These are definitely bugs. Sorry I did not test more thoroughly. The good news is I know what the problems are, and I am working on fixing them now.

**Comment by ctrueden** [comment]
I pushed some fixes. Notes:

* If your script has no declared outputs, then it implicitly has one output named `result` which equals the return value of your script (or null if none).
* Null outputs are not displayed, nor is any warning issued regarding them. (This was true before these fixes—but it is important for understanding the behavior of scripts overall.)
* The IJ1 macro language only supports string constant return values via the `return` statement. But you can write `result = myExpression(foo, bar);` or whatever during the macro, and then that value will be used instead of the actual return value.
* The magic value `-17974594` (a.k.a. `0xfeedbabe`) has been eliminated; it was not actually necessary to make the IJ1 macro language work as desired.
* The IJ1 macro language is now much closer to JSR-223 compliant: instances of `IJ1MacroEngine` keep their engine-scope `Bindings` in sync with `ij.macro.Interpreter` instances that evaluate each macro. Among other benefits, this squashes bugs triggered by macros that issue `return` statements, where output values would not be properly known afterward.

I also pushed a commit to the `scijava/scripting-jython` project which fixes the decoding of `JyInteger` and other primitive wrapper types. However, you will still see messages like:
```
[WARNING] Ignoring unsupported output: intValue [java.lang.Integer]
[WARNING] Ignoring unsupported output: doubleValue [java.lang.Double]
```
because at the moment, the SciJava Common library does not provide a display which handles numbers. There is only `TextDisplay` typed on `String`. Really, we should generalize that to `ObjectDisplay` and have it handle any object via calls to `toString()`—but with very low priority so that other displays can take precedence first if they exist.

**Comment by ctrueden** [comment]
I will cut new component releases tomorrow, and upload them to the Java-8 update site.

**Comment by haesleinhuepf** [comment]
Cool. Thank you very much for fixing and thanks for the explanation!

**Comment by ctrueden** [comment]
I delayed cutting releases by one day because I decided to address the `Ignoring unsupported output` warnings. It was ridiculous that the framework had no plugins to display numeric or boolean results. So I am coding a new thing that does it. Almost ready...

**Comment by ctrueden** [comment]
Everything is released and uploaded!

There is now a snazzy new aggregated table which pops up when you have simple outputs (numbers, booleans, and/or text):

![stuff-script](https://cloud.githubusercontent.com/assets/556626/18218007/9bb1c212-7125-11e6-8e21-4028d5849455.png)
![stuff-output](https://cloud.githubusercontent.com/assets/556626/18218010/9e4cc3b4-7125-11e6-8bfd-3c8e939177fa.png)

There is only _one_ bug left I failed to quash before releasing: if you rely on the default "single output named `result`" behavior, it will not show the table, but rather still show the annoying "Ignoring unsupported output" message. I have already fixed it on the master branch (imagej/imagej-common@e3f65c4cb9e1dacaa31bd1915377a6b7b37a91ac) but I did not want to immediately cut another three releases just to fix this relatively tiny bug. It will get included in the next round of bug-fixes.
