### ISSUE TITLE
ImageJ does not run with java 10 on Linux

### ISSUE THREAD

**Issue by aliencam** [imagej/imagej#195]
I am on Arch Linux with the "jre10-openjdk" java environment. 
Starting imagej: 
```
#imagej $ imagej
Open other images in this ImageJ panel as follows:
  imagej -p 1 <image1> [<image2> ... <imageN>]

Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
/usr/bin/imagej: line 1: : No such file or directory
```
imagej does not start erroring out because the -d64 option does not exist in jre10 . 
 installing jre8-openjdk and setting jre8 as the default java environment solves the issue. 
```
$ sudo pacman -S jre8-openjdk
$ sudo archlinux-java status
Available Java environments:
  java-10-openjdk (default)
  java-8-openjdk/jre
$ sudo archlinux-java set java-8-openjdk/jre
$ imagej
Open other images in this ImageJ panel as follows:
  imagej -p 1 <image1> [<image2> ... <imageN>]

/usr/bin/imagej: line 1: : No such file or directory
```
Then everything works fine.  

I will report to the arch user repository that dependencies should be specifically earlier than jre10-openjdk.  https://aur.archlinux.org/pkgbase/imagej

**Comment by ctrueden** [comment]
The error is caused by the `imagej.sh` Unix launcher, which is not an official part of ImageJ (neither ImageJ1 nor ImageJ2). If you clone `https://aur.archlinux.org/imagej.git` as linked from the package page, you can examine the source and find the place where `-d32` or `-d64` gets added to the arguments. The proper fix is to fix the launcher, not downgrade the dependencies.

If you download Fiji from https://fiji.sc#download, it should work with Java 10. (If the bundled launcher does not work with Java 10, try the 5.0.0 release version [here](http://maven.imagej.net/service/local/artifact/maven/redirect?r=releases&g=net.imagej&a=imagej-launcher&v=5.0.0&e=exe&c=linux64).)

I do not recommend installing ImageJ from a Linux package manager, because it creates a system-wide installation that does not allow users to easily manage and install their own plugins. The packages available on the various Linux distros were not created nor maintained by, nor in collaboration with, the core ImageJ developers. Furthermore, these packages install plain ImageJ 1.x, not ImageJ2. Whereas this repository here is for ImageJ2.

**Comment by aliencam** [comment]
Okay great, thanks for your recommendations!

**Comment by giancarlotamburello** [comment]
In linux, the error can be fixed by editing _/usr/bin/imagej_ file as superuser. It is better to backup the file in your home:

`cp /usr/bin/imagej /home/yourusername/imagej.bk`

Then, edit the file as superuser

`sudo nano /usr/bin/imagej`

And remove the variable _${arch}_ from 2 lines of command at the end of the script. It seems that this version of Java does not recognize the option _-d64_ (see the error _Unrecognized option: -d64_).
