### ISSUE TITLE
Getting to the Searchbar with L

### ISSUE THREAD

**Issue by hyungsongnam** [imagej/imagej#206]
Hello,
I would like to report a minor UI issue.
With an image window open, typing L goes to the searchbar.
This also works when the Window & Level tool is open and is in the foreground.
However, when the Channels tool is open and in the foreground, typing L doesn't go to the searchbar.

Thank you!

**Comment by ctrueden** [comment]
@hyungsongnam Thanks for the report! And sorry for the delay in reply. Interesting observation. It seems that none of ImageJ's shortcuts work as expected from the Channels window. For example, pressing ENTER does not raise the main window, pressing Shift+B (or Ctrl+Shift+B) does not open Blobs, and so forth. So this problem is more general than just the search bar.

@rasband Any idea why the Channels window behaves differently than e.g. B&C? Maybe a key listener is not added to the Channels window?

**Comment by rasband** [comment]
The latest ImageJ daily build (1.52h37) adds key listeners to all the components of the "Channels" Dialog, which appears to fix this problem. View the source code changes at https://github.com/imagej/imagej1/commit/2c43bef4d5fc4521d5aecbe4f3b8f5282f4e761a.
