### ISSUE TITLE
The new command finder built into the status bar is somewhat broken

### ISSUE THREAD

**Issue by acardona** [imagej/imagej#217]
If I write "script" and push return it launches the first listed item in the *unfocused* window that pop up under the text field.

The old "Find Commands..." is still there, under "Plugins - Utilities". Typing "script" there lists many more entries than in the new system.

What was the rationale for setting the new find commands system as the default for the key binding "L", when it is so different, and limited, compared to the old one?

In addition, the new one has an ImageJ2 flavor to it. I did not enable ImageJ2, therefore, why am I seeing it at all?

It is also rather weird that the search field is not replicated in the window itself. Makes for awkward navigation, also, one can't just move to the search field with the up arrow when at the top of the list of results, like used to be possible in the old one (that functionality seems to have been broken too).

Also, the text field of the new one doesn't lose focus, so typing the key binding listed in the info panel for a script doesn't open it: it adds the key to the search text field, which destroys the prior search.

It is also not obvious that the "..." button inside the info panel actually launches an options dialog for the new search functionality. It should be a big named button at the bottom, for enhanced discoverability.

Also rather concerning, the placement of the search text field in the ImageJ status bar occludes the text messages in the status bar, which is undesirable. For example, double-click to read the memory and JVM version, and you can't: it's garbled over the search text field.

It is looking like the new Find Commands tool underwent limited usability testing and was rushed through the door. It is not ready, and should be optional (rather than bound to "L" by default) until it undergoes substantial improvement.

**Comment by ctrueden** [comment]
> If I write "script" and push return it launches the first listed item in the unfocused window that pop up under the text field.

If the fact that the results window is unfocused bothers you, you can check the "Embed search results in main window" option to make the search results appear as part of the main window. The downside is that it will then be width-limited by the current width of the main window.

> The old "Find Commands..." is still there, under "Plugins - Utilities". Typing "script" there lists many more entries than in the new system.

I looked into this. The entries beneath the _Help > Examples_ submenu are not being indexed by the search bar, because ImageJ2 is somehow not discovering them as ImageJ1 commands. I wonder if ImageJ1 creates those menu items differently than the rest of the menu. I filed imagej/imagej-legacy#204 to track this problem.

> What was the rationale for setting the new find commands system as the default for the key binding "L", when it is so different, and limited, compared to the old one?

Because it is more approachable for new users, more powerful for power users, and extensible for developers. You can write your own `Searcher` plugins to extend the results shown by searches, and your own `SearchActionFactory` plugins to add available actions—e.g., the Source button that shows the source code online on GitHub.

> In addition, the new one has an ImageJ2 flavor to it. I did not enable ImageJ2, therefore, why am I seeing it at all?

Fiji is fundamentally built on ImageJ2 since 2014. So I do not know what you mean by "I did not enable ImageJ2."

You can disable the search bar by changing the "Search bar style" to None, and unchecking "Pressing L focuses the search bar", in the _Edit > Options > Search Bar..._ menu (the same menu as the "..." button in the search results panel).

> It is also rather weird that the search field is not replicated in the window itself.

Try enabling the "Embed search results in main window" option.

> one can't just move to the search field with the up arrow

The search field is already focused; there is no need to move to it.

> Also, the text field of the new one doesn't lose focus, so typing the key binding listed in the info panel for a script doesn't open it: it adds the key to the search text field, which destroys the prior search.

I typed "blobs" in to the search box, and saw that "meta shift B" is the shortcut. Pressing that key combo did open Blobs. Perhaps it behaves differently on Linux. But I don't think this is a big problem because you can simply hit <kbd>ENTER</kbd> to run the command. You can also lose the focus from the search box by pressing <kbd>Esc</kbd> twice.

> It is also not obvious that the "..." button inside the info panel actually launches an options dialog for the new search functionality. It should be a big named button at the bottom, for enhanced discoverability.

I tried to make the button the gear symbol (⚙) but unfortunately, it is too new of a Unicode symbol to work with Swing. So we compromised on "..." instead. You can also access the search options via the _Edit > Options > Search Bar..._ menu, just like most other ImageJ options.

> Also rather concerning, the placement of the search text field in the ImageJ status bar occludes the text messages in the status bar, which is undesirable. For example, double-click to read the memory and JVM version, and you can't: it's garbled over the search text field.

Change the "Search bar style" to Full instead of Mini and the search bar will take up a full line beneath the status bar. Or you can widen your main window.

> It is looking like the new Find Commands tool underwent limited usability testing and was rushed through the door. It is not ready, and should be optional (rather than bound to "L" by default) until it undergoes substantial improvement.

There was a lot of testing, by several people. Since the search bar was released, many people have expressed a lot of appreciation for it. I use it very frequently, and strongly disagree with your assessment of its readiness. Nearly all of your complaints are specifically addressed by the options in the _Edit > Options > Search Bar..._ dialog. I am disappointed that you do not find it to be an improvement over the old Command Finder, but that's why the option still exists to revert back.

**Comment by acardona** [comment]
Hi Curtis,

I didn't expect less than a lot of pushback on my comments. I understand you and others have invested into the new command finder and prefer it. I don't. I understand I am not maintaining Fiji/ImageJ and therefore it's up to you to call the shots. Fine with me. I will still report the brokenness. I disagree that the new command finder is more 

On the brokenness, thanks for filing the one issue you agreed its worth fixing. Would be nice if the authors of the new find command GUI would follow it up, rather than abandon it for a year like the issues with the new Script Interpreter.

The "Embed search results in main window" is, in my view, the opposite approach of what would be desirable: to embed the search field into the search results window.

Similarly, making the search field be as large as the whole ImageJ status bar is not the solution. The ImageJ status bar has had its function for decades, and I find adding the search field to it unpleasant and a distraction.

Also, it is a poor default choice that the status bar text is garbled over the search field. Instead, the default should be that the search field is embedded in the search window that opens upon pressing enter.

I do not know how many and what kind of user or developer tested the search bar, the fact remains it has poor defaults and poor design choices that are a step back from the brilliant design by Marc Longair. Thanks for at least not removing Marc's Find Commands UI, so I can go back to using it after having discovered, through this bug report, that I can disable the "L" shortcut.

Apparently I can't get rid of the search bar in the status window, and that, please, file it under an urgent feature request.

**Comment by ctrueden** [comment]
You have written a lot of text but there are few clearly articulated nor agreed upon technical actions to be taken here. Imagine I were to file an issue in the TrakEM2 repository entitled "TrakEM2 sucks" with a litany of complaints. It would be a terribly structured and unhelpful issue, which should be swiftly closed in favor of specific technically-oriented concerns that can be realistically addressed.

> Would be nice if the authors of the new find command GUI would follow it up, rather than abandon it for a year like the issues with the new Script Interpreter.

Do you think I don't want to work on it? Of course I do! But as I said, I have a [huge number of things on my plate](https://waffle.io/ctrueden/tasks), and I simply do not have time to address the Script Interpreter issues when there so many other tasks with higher severity, higher impact, more users depending on it, politely requested, etc.

Since the Script Interpreter is a developer tool, I was really hoping that some other devs such as yourself would be able to step up and offer PRs to improve it, rather than only bullying me into working on it alone. Clone the [scijava/script-editor](https://github.com/scijava/script-editor) repository and take a look at [`InterpreterPane`](https://github.com/scijava/script-editor/blob/script-editor-0.3.0/src/main/java/org/scijava/ui/swing/script/InterpreterPane.java) and [`InterpreterWindow`](https://github.com/scijava/script-editor/blob/script-editor-0.3.0/src/main/java/org/scijava/ui/swing/script/InterpreterWindow.java). Use [`ScriptInterpreterTestDrive`](https://github.com/scijava/script-editor/blob/script-editor-0.3.0/src/test/java/org/scijava/ui/swing/script/ScriptInterpreterTestDrive.java#L50-L63) to test out any changes in the IDE.

I will not allow you to shame me into prioritizing your pet issues when I am already doing the best that I know how every day for this community. All you are achieving with your incivility is to deflate my enthusiasm for working on ImageJ and Fiji at all. You would be much better served by instead focusing your time and energy toward constructive improvements to the codebase.

Do not reopen this issue again, nor any issue of this nature. If you have a specific technically-oriented concern, file an issue describing the problem matter-of-factly, without judgment or accusation. If you want to improve a particular aspect of ImageJ more broadly, great—start a discussion on the [Image.sc Forum](https://forum.image.sc/) presenting your idea framed as a positive step forward, rather than verbally trashing all of the hard work people have invested thus far.

**Comment by frauzufall** [comment]
Hey, another dev here who was involved in building the search bar. Writing essays like this will not motivate developers (at least not me) to spend time addressing your concerns. Thanks @ctrueden for answering in detail anyways. As he said, the forum might be a better place to discuss general strategies.
