### ISSUE TITLE
Mirror https://romulus.oice.uni-erlangen.de/maven/repository on maven.imagej.net

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej#235]
This would make the `3D_Animation_*` artifacts by @bene51 available for other projects without the need of adding another repository to their configuration.

See https://github.com/bene51/3Dscript/issues/2#issuecomment-447306360.

**Comment by ctrueden** [comment]
I added the mirror, but it is not immediately detecting the served artifacts. I'll see if it's up and running tomorrow.

Meanwhile, I have some concerns (mostly for @bene51):

* The URL for that Maven repositories seems very temporary. If it goes out of service, then maven.imagej.net will end up being the sole way to access those artifacts going forward. As such, why not just deploy to maven.imagej.net in the first place and dispense with running your own (unstable-looking) Maven repository?
* The artifacts served there use groupId `sc.fiji`, but are not Fiji-related projects. Please use a different groupId reflecting your organization, rather than co-opting the Fiji one.

**Comment by ctrueden** [comment]
I don't think the proxy is working. This might be because the index update mechanism of maven.imagej.net is currently broken (on my list to fix it...). Or it might be because the romulus repo is missing some key functionality or structure.

@bene51 If you see this: please consider deploying your artifacts to maven.imagej.net directly instead of running your own repo. Happy to discuss on forum.image.sc if you have questions or concerns.

**Comment by bene51** [comment]
I'm happy to directly deploy it to maven.scijava.org. I think I have mainly three questions:
- How do I do it? I guess I need an account to create a repository there, right? How can I get an account?
- How can I then deploy to it? I guess there must be some documentation somewhere, but couldn't actually find anything neither in the forum directly nor with google, at least not ImageJ related. Do you have one or two links for me?
- regarding artifact naming: I agree with you, but renaming it now means that also package names need to be renamed, which basically breaks any code that might have been written in the mean time. Any recommendations?

Thanks

**Comment by ctrueden** [comment]
The fact that all the 3Dscript projects are in one Git repository will almost certainly confuse the Travis CI scripts I wrote. Sorry for the bad news about that. If you still want to deploy to maven.scijava.org directly, the best way forward would be to model things after the way other SciJava-based projects are structured. But I understand if you don't have time.

I'll try to make another stab at getting the proxy working soon...

**Comment by ctrueden** [comment]
I finally learned why the proxy wasn't working: I never added it to the public group. 🤦  I have now done so. And it works! :tada:

```
: curtis@sirius ~/code/imagej/imagej (master*) »
mvn dependency:get -Dartifact=sc.fiji:3D_Animation:0.1
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< net.imagej:imagej >--------------------------
[INFO] Building ImageJ 2.0.0-rc-73-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.2:get (default-cli) @ imagej ---
[INFO] Resolving sc.fiji:3D_Animation:jar:0.1 with transitive dependencies
Downloading from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation/0.1/3D_Animation-0.1.pom
Downloaded from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation/0.1/3D_Animation-0.1.pom (3.3 kB at 547 B/s)
Downloading from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation_Language/0.1/3D_Animation_Language-0.1.pom
Downloaded from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation_Language/0.1/3D_Animation_Language-0.1.pom (3.1 kB at 792 B/s)
Downloading from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation/0.1/3D_Animation-0.1.jar
Downloading from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation_Language/0.1/3D_Animation_Language-0.1.jar
Downloaded from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation_Language/0.1/3D_Animation_Language-0.1.jar (141 kB at 29 kB/s)
Downloaded from scijava.public: https://maven.scijava.org/content/groups/public/sc/fiji/3D_Animation/0.1/3D_Animation-0.1.jar (203 kB at 41 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.609 s
[INFO] Finished at: 2020-06-13T12:09:40-05:00
[INFO] ------------------------------------------------------------------------
```
