### ISSUE TITLE
ij.macro.Functions disappeared after compilation in Eclipse

### ISSUE THREAD

**Issue by shenghuanjie** [imagej/imagej#236]
1. I downloaded the source code from here. version 1.52o
https://imagej.nih.gov/ij/download/src/

2. I followed the following instruction to create a ImageJ project in Eclipse on Windows 10.
http://imagejdocu.tudor.lu/doku.php?id=howto:plugins:the_imagej_eclipse_howto

3. When I tried to compile the source code using the default Java Builder, Function.class in ij.macro gets generated and then automatically deleted.  Therefore, I cannot run macro in the compiled ImageJ in Eclipse. Other functions seem to be fine.  There is error message during compilation in Eclipse.

4. I also tried the given ant file `build.xml` but it doesn't work.

5. Previous versions like 1.51h works fine.

**Comment by imagejan** [comment]
Instead of downloading from imagej.nih.gov, I'd recommend starting from the mavenized version of ImageJ 1.x:

https://github.com/imagej/ImageJA

In Eclipse, you can just *Import... > Maven > Existing Maven Projects...* and it should work just fine.

See https://imagej.net/Developing_ImageJ_in_Eclipse for more instructions.

**Comment by ctrueden** [comment]
I'm closing this issue, since @imagejan's advice should solve the problem. If you really want to do things according to the old imagejdocu.tudor.lu approach, then please open the issue at https://github.com/imagej/imagej1/issues instead, since that is the repository for "pure ImageJ 1.x" support.
