### ISSUE TITLE
I am using ij.jar in java mode, the java code is:IJ.run(imp, "Auto Threshold", "otsu white"); but get Unrecognized command: "Auto Threshold",how to resolve this question??

### ISSUE THREAD

**Issue by JanLiao** [imagej/imagej#246]

**Comment by ctrueden** [comment]
The "Auto Threshold" command is not a core ImageJ 1.x plugin. It is part of Fiji: https://github.com/fiji/Auto_Threshold

So you'll need to have the Auto Threshold plugin available to your ImageJ. Normally in Java, this means adding Auto_Threshold-1.17.1.jar and its dependencies to your runtime classpath.

However, for ImageJ1 plugins like this, it is not enough to put the plugin on your classpath, because ImageJ 1.x does not discover plugins that way—only via the `plugins.dir` system property.

So you have to do something like this:
```java
mkdir ~/app
cd ~/app
cp /path/to/Fiji.app/jars/ij-1.52p.jar /path/to/Fiji.app/plugins/Auto_Threshold-1.17.1.jar .
javac -cp ij-1.52p.jar ThresholdImage.java
java -cp ij-1.52p.jar:Auto_Threshold-1.17.1.jar:. -Dplugins.dir="$HOME/app" ThresholdImage
```
This assumes:
1. You have a Fiji installation at `/path/to/Fiji.app` (change the commands above to match yours), from which you will steal the needed JAR files.
2. You are using a *nix shell (Linux, macOS, Windows Subsystem for Linux, Git Bash, Cygwin, etc.). With Windows CMD or PowerShell the commands are different.
3. The contents of `ThresholdImage.java` is:
    ```java
    import ij.IJ;
    import ij.ImagePlus;
    public class ThresholdImage {
      public static void main(String... args) {
        new ij.ImageJ();
        ImagePlus imp = IJ.openImage("/path/to/data/image.tif");
        IJ.run(imp, "Auto Threshold", "otsu white");
      }
    }
    ```
    Where `path/to/data/image.tif` is the image you want to threshold.

Note that ImageJ2 has [a patch addressing this limitation](https://github.com/imagej/imagej-legacy/blob/imagej-legacy-0.37.2/src/main/java/net/imagej/legacy/DefaultLegacyHooks.java#L330-L354), so that you can run plugins present on the classpath without setting `plugins.dir` to a local file path.

Finally, all of this is a rather low-level way of doing things. I'd encourage you to use Maven with a proper pom.xml to manage your dependencies, since copying JARs manually becomes burdensome quickly. See [example-imagej-command](https://github.com/imagej/example-imagej-command) and [example-legacy-plugin](https://github.com/imagej/example-legacy-plugin) for starting points.
