### ISSUE TITLE
Fix "Run single instance listener" feature

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#98]
As [reported on the mailing list](https://list.nih.gov/cgi-bin/wa.exe?A2=IMAGEJ;1adb9e44.1407), at least on Windows, the "Run single instance listener" option does not work.

**Comment by manerotoni** [comment]
Hi dscho,
here at EMBL, Heidelberg, we also used the single instance ImageJ to call a script from another program. At the moment I just reverted to IJ1 but this is definitely not a solution.
May be there is another way? for instance build a socket communication with Fiji and send commands, scripts through it. 

Thanks

Antonio

**Comment by ctrueden** [comment]
@manerotoni: Realistically, there is no one on the core development team who can reimplement this feature for ImageJ2 any time soon. However, pull requests are very welcome. The patch would go in the ImageJ Legacy component's [LegacyCommandline](https://github.com/imagej/imagej-legacy/blob/imagej-legacy-0.11.0/src/main/java/net/imagej/legacy/LegacyCommandline.java) class. A starting point is the [OtherInstance](https://github.com/imagej/ImageJA/blob/v1.49m/src/main/java/ij/OtherInstance.java) class of ImageJ1, which would need to be adapted for use in ImageJ2. The `OtherInstance` code takes care to connect to the existing ImageJ1 instance in a secure (local and user-specific) way, so is worth studying.

**Comment by ctrueden** [comment]
Fixed by imagej/imagej-legacy#116.

**Comment by naikymen** [comment]
Hi! I was just trying to open some images from the command-line in linux, in an existing FIJI instance.

The relevant checkbox under `Edit -> Options -> Misc...` is checked.

However, after starting FIJI with `./ImageJ-linux64`, and running `./ImageJ-linux64 images/icon.png`, another instance is started instead of using the previous one.

After reading #184, I figured that it is not the expected behavior.

If I try using the `--ij1` flag to launch FIJI, or if I try using ImageJ1, the image opens as expected. This is sufficient for my current need, but I'd prefer using FIJI instead.

Is there a way of opening images in an existing instance of FIJI? Was the feature removed?

I'm using GNU/Linux.

> PS: Thanks for all the work on ImageJ :)
